### ISSUE TITLE
Caffe cannot be imported

### ISSUE THREAD

**Issue by GKalliatakis** [CSAILVision/NetDissect#2]
Where should I put the cloned repo inside the compiled caffe folder in order not to get the import error of no module named caffe?

I have already matcaffe and pycaffe compiled in that folder.

**Comment by davidbau** [comment]
Make sure your PYTHONPATH has caffe's python folder in it, e.g.,

```
CAFFE_HOME=/usr/local/caffe # or wherever your caffe is
PYTHONPATH=${CAFFE_HOME}/python:${PYTHONPATH}
```

**Comment by GKalliatakis** [comment]
I have tried export PYTHONPATH=path/to/caffe/python:$PYTHONPATH

But I get the same error..Any other thoughts?

**Comment by GKalliatakis** [comment]
I manage to fix the error. The caffe Python module was not properly installed at first place.
