### ISSUE TITLE
About Figure 10 in the paper (Number of unique detectors vs Training iteration)

### ISSUE THREAD

**Issue by Jiangfeng-Xiong** [CSAILVision/NetDissect#3]
Hi,
First of all, thank you for your amazing work.
How can I get the figure below in the paper? Is it available in this repository?
![image](https://cloud.githubusercontent.com/assets/18069771/26521528/fcba4326-431c-11e7-89cf-0d116764eb73.png)

**Comment by zhoubolei** [comment]
You need to save the snapshots at each epoch during the training, then run netdissect on each one of them. After that you could plot the figure like this.
