### ISSUE TITLE
Caffe import is unnecessary and not used

### ISSUE THREAD

**Issue by mlosch** [CSAILVision/NetDissect#9]
https://github.com/CSAILVision/NetDissect/blob/6c6fc51a45b6d6bfc78b83c9b372ae04cb94ffc6/src/netprobe_pytorch.py#L19

Line 19-21 and 32-33 can be removed without harming the functionality.

**Comment by zhoubolei** [comment]
Thanks for reporting the issue. I fixed it. The pytorch version of netdissect is still in beta test. Please let us know if there is other issue.
Bolei
